### ISSUE TITLE
`create-sibling-webdav` command cannot identify dataset - related to EnsureDataset constraint

### ISSUE THREAD

**Issue by mslw** [datalad/datalad-next#225]
### Problem
It should be possible to call `create-sibling-webdav` without specifying the dataset explicitly ("If no dataset is given, an attempt is made to identify the dataset based on the current working directory"), as long as the working directory is inside the dataset, like in the first example from the manpage:

```
datalad create-sibling-webdav "https://webdav.example.com/myds"
```
But, using current `main`, this gives:
```
[ERROR  ] 'NoneType' object has no attribute 'ds' 
```

### Description
The error is coming from https://github.com/datalad/datalad-next/blob/bc979ab85701226f0c3814c89606f34c09072d2f/datalad_next/commands/create_sibling_webdav.py#L289

The `CreateSiblingWebDAV` class is derived from `ValidatedInterface`; `EnsureDataset` constraint is used; the `__call__` has a default value `dataset=None` (abbreviated below):

```
class CreateSiblingWebDAV(ValidatedInterface):
    _params_ = dict(
        ...
        dataset=Parameter(...)
        ...
    )

    _validator_ = CreateSiblingWebDAVParamValidator(dict(
        ...
        dataset=EnsureDataset(installed=True, purpose='create WebDAV sibling(s)')
        ...
    )

    def __call__(
            url,
            *,
            dataset=None,
            ...
    ):
        ds = dataset.ds
```

Now, if I understand correctly the [ValidatedInterface](http://docs.datalad.org/projects/next/en/latest/generated/datalad_next.commands.ValidatedInterface.html) documentation, if `dataset` is not given (optional), it gets to the validator as None, but because this matches the default value in `__call__`, it just passes through. Then, the attempt to obtain the `dataset.ds` property crashes.

#168 gives me an impression (possibly wrong) that the use of `require_dataset` (which should try to figure out the path, right?) is discouraged, and `EnsureDataset` was meant to replace it. But this doesn't seem to be the case: I tried naively removing the default value for the dataset, but it ended with  an error "Validation of parameter 'dataset' failed -caused by- Cannot create Dataset from <class 'NoneType'>".

Edit: I re-read `EnsureDataset` and realised that it calls `require_dataset`, but it first checks whether the argument is `str` or `PurePath`. If I changed that to also allow `None`, and removed the defaul value in `__call__` it would probably work, (at least from CLI) but would that be intended way?

How to restore the "figuring-out-based-on-workdir" behaviour?

**Comment by mih** [comment]
Thanks for raising this issue -- and doing it now!

I looked at the code and altered a unit test to expose the issue there too.

Two conclusions:

1. `create-sibling-webdav` is broken, because it violates the condition:

> a command implementation must always be able to handle its own defaults directly, and cannot delegate a default value handling to a constraint

2. I think this condition is suboptimal for the exact rational you posted. it would lead to code duplication.

Right now I think the following changes should be made:

- the logic in `EnsureCommandParameterization.__call__` needs to consider an additional switch (per parameter constraint) that forces a constraint to also process a default parameter value
- whether or not this is needed or possible is outside the scope of an individual constraint, and must be configurable in `EnsureCommandParameterization`. Likely its `__init__` needs to get a `validate_default=` parameter that receives a set of parameter names for which the default rules is not applied
- `EnsureDataset` must be able to handle a `None` parameter value and return the Dataset in the CWD (if there is any)


ATM I have no elegant solution for the following problem:

- I believe most default values require no validation -- hence the current rule still makes sense
- Most commands have a `dataset` parameter that will require the proposed exception

So it would make sense to say `validate_default=set(['dataset'])` as a standard. However, for most commands that need something different than that, it would require to re-specify the default set-item.

**Comment by mslw** [comment]
I agree!

If the goal is to move `require_dataset` out of the `__call__()` body and into the validator (while keeping the pattern of using default `dataset=None` to mean that it needs to be figured out), then an exception needs to be made when it comes to default values passing through the validator.

I did not read the validator implementation, but your suggestion to add a `validate_default=` parameter to `EnsureCommandParameterization` sounds elegant to me.

I do not, however, feel that it necessarily has to have a default value. If it's an exception to the rule, then maybe better to keep it explicit always? Even if looking purely at the lines of code required, this would still be a gain (one parameter to validation versus a conditional statement in command call body).
