### ISSUE TITLE
Clarify behaviour of type-hinting `__call()__` methods with decorators

### ISSUE THREAD

**Issue by jsheunis** [datalad/datalad-next#363]
E.g. parameter validation/coercion of `ValidatedInterfaces` in `datalad-next` happens  inside a decorator to `__call__`. Either type-hinting should declare what actually reached `__call__()`, or it should declare what the outer-shell of `__call__()` before decorators can handle. This is untested and undocumented.

**Comment by mih** [comment]
This is not specific to `ValidatedInterfaces`. The standard `Interface` of any command in core also puts `__call__` behind decorators.

I believe/speculate that any type-hinting in the signature of `__call__` must indicate what that method can actually take. It should *not* consider any decorators. A decorator wraps a callable and returns another. The function returned by the decorator also needs its own type annotations that could be arbitrarily different. This is evident for any datalad command, because some of the standard arguments supported by every command are not even included in the signature of `__call__`.

The generic nature of the `__call__` wrapping in datalad makes it rather hard to perform correct type-annotation, and the cost/benefit trade-off seems to be questionable -- at least given my skillset.

**Comment by jsheunis** [comment]
Ok, i have spent enough time reading a bunch of docs on the internet and it seems the general idea is that the `__call__()` method of the class should have type hints based on its original signature, regardless of what the decorator does internally and hence regardless of what eventually reaches `__call__()`. I.e. since the parameter validation and coercion steps happen inside the decorator function, the decorator itself will ensure that the correct types are passed to the `__call__()` method, but type hinting should reflect the expected types before the decorators are applied.

Two motivations for this seems to be that:
- this provides meaningful type information to other developers and tools
- apparently, type checking should be able to help catch potential type-related errors at the earliest possible stage

**Comment by mih** [comment]
Actually, this sounds like a complete contradiction of my interpretation. I was speculating that:

- if the decorators would be removed, there would be no need to adjust the type-hinting, because it is focused on the **innermost** shell/function-body.

I read your statement as:

- if the decorators would be removed, there would be need to adjust the type-hinting, because it is focused on the **outermost** shell/decorated function.

**Comment by jsheunis** [comment]
There's a miscommunication somewhere, because I agree with you on this:

> if the decorators would be removed, there would be no need to adjust the type-hinting, because it is focused on the innermost shell/function-body.

So I guess my wording of "..but type hinting should reflect the expected types before the decorators are applied..." is ambiguous.

In summary, I agree with you.

**Comment by mih** [comment]
Discussed in dev call. Verdict: too complex to have actual value considering the anticipated costs.
