### ISSUE TITLE
Replace `IterableSubprocessError` with `CommandError`?

### ISSUE THREAD

**Issue by mih** [datalad/datalad-next#567]
@christian-monch with the recent changes in subprocess execution also came a switch to a different core exception type. I think we should question this "side effect".

`datalad-core` has `CommandError`. It is much more widely used (obvsl). Importantly, it is directly supported by the CLI.

`IterableSubprocessError` OTOH is much leaner and more directly tuned to the capabilities of the new code.

However, in detail it would be minimal effort to sync these. We would need to

- have `IterableSubprocessError` support `.code` (currently it has `.returncode`)

Type-wise the situation is more tricky. `CommandError` is a `RuntimeError` subclass. `IterableSubprocessError` is a `SubprocessError` subclass. The latter seems more sensible. `SubprocessError` was introduced with PY3.3, and is itself a direct `Exception` subclass.

Intuitively, I'd say that we should embrace the `subprocess` exception interface and naming conventions, but also add the richness of reporting from `CommandError` (CWD, a context message, standardized rendering).

Maybe it would make sense to base off of `subprocess.CalledProcessError`, and had detection for that to datalad-core's CLI (such that we do not need to import `datalad-next` code into it.

**Comment by christian-monch** [comment]
I am not sure that I completely understand the proposal. The title says "replace `IterableSubprocessError` with `CommandError`". The rationale in the description, IIANM, is that the exception could leave `datalad-next` code and be properly processed by `datalad-core`-code, especially by the CLI-code, without any changes to `datalad-core`.

If that is the intention, should we not raise `CommandError` instead of `IterableSubprocessError` in the implementation of `iterable_subprocess`?

Or did I misunderstand the issue description?

**Comment by christian-monch** [comment]
I think it makes sense to consider the following options:

#### 1. Use `CommandError` instead of `IterableSubprocessError` in `iterable_subprocess`.

(Probably the simplest unification approach)

+ Compatibel with datalad-core (CLI)
+ Supports added feature `cwd`
- Keeps `RuntimeError`-based exception hierarchy
 
Costs: Requires changes in datalad-next (about a dozen usages), no changes in datalad-core.


#### 2. Base `CommandError` on `SubprocessError` & 1. (use `CommandError` in `iterable_subprocess`)

+ Compatibel with datalad-core (CLI)
+ Supports added feature `cwd`
+ Conforms to exception standard set in `subprocess`, i.e. sub process errors are subclasses of `SubprocessError`.

Costs: requires changes in datalad-next (same as in "1. Use CommandError instead ..." above), requires changes in datalad-core (about 120 usages)


#### 3. Base `CommandError` on `CalledSubprocessError`  & 1. (use `CommandError` in `iterable_subprocess`)

+ Compatibel with datalad-core (CLI)
+ Supports added feature `cwd`
+ Conforms to exception standard set in `subprocess`, i.e. sub process errors are subclasses of `SubprocessError`.
- Integration of `CommandError` and `CalledProcessError` is required, e.g. changing `code` to `returncode`, `stdout` to `output`, etc.

Costs: with proper subclassing (changing `code` to `returncode` etc.), a large number of changes in datalad-core can be expected.


##### Conclusion:

I would suggest to implement option "1." for now. At a later point in time, datalad-core could either implement option "2." or option "3.", which should then be transparent to datalad-next.

**Comment by mih** [comment]
What if provide a new class that derives from `SubprocessError` AND `CommandError` to make type comparisons work for both code bases. And then we aggressively overwrite/alias any functionality that is conflicting/duplicate?

We could also leave `IterableSubprocessError` untouched, catch it in `iter_subproc` and recode to this new class.

**Comment by christian-monch** [comment]
> What if provide a new class that derives from `SubprocessError` AND `CommandError` to make type comparisons work for both code bases. And then we aggressively overwrite/alias any functionality that is conflicting/duplicate?
> 

We could do that, but to me, that seems like a workaround instead of putting in the work to do the "correct" thing (whatever that will be). It sounds like a recipe for building technical debt. I think that the changes in the datalad-next code base that would be required to support `CommandError` or something similar are modest.

> We could also leave `IterableSubprocessError` untouched, catch it in `iter_subproc` and recode to this new class.

Generally, it seems to me that we want to prevent putting `CommandError` into datalad-next, or ---more specifically---  into `iterable_subprocess`. But I would not opt for "translating" from one `IterableSubprocessError` to another `*Error`-class. That increases the complexity and the possibility of errors. Also, if we create the `*Error`-objects in `iterable_subprocess`, we have the most comprehensive context available, and could therefore create the most detailed error information.


I might have misunderstood something, but I would not use multiple inheritance to prevent changing the code, and I would not translate errors, if we can directly create objects of the target error class

**Comment by mih** [comment]
OK, so this needs a resolution before the 1.1 version can be released. Still not sure what is optimal here. I think requiring changes to datalad-core means unforeseeable timing of a resolution.

**Comment by christian-monch** [comment]
> OK, so this needs a resolution before the 1.1 version can be released. Still not sure what is optimal here. I think requiring changes to datalad-core means unforeseeable timing of a resolution.

I think so too. How about a pragmatic approach? We adopting option 1. from above, i.e. raising `CommandError` in `iterable_subprocess`. That should not take much effort. I have a branch that has changes here: https://github.com/christian-monch/datalad-next/tree/move-to-command-error

**Comment by christian-monch** [comment]
> Post as a PR?

Will do

**Comment by mih** [comment]
#579 is merged
