### ISSUE TITLE
`PersistentSubShell` feature

### ISSUE THREAD

**Issue by mih** [datalad/datalad-next#572]
Let's start with the thing itself only, and not a full set of abstractions.

- [X] focus on POSIX shell clients 
- [X] methods to execute a command with support for iterator for stdin and reading stdout/err, and report the return code
- [ ] need not work with any shell, but should be explicit what shells with which params are compatible
- [X] should work with such a shell executed via ssh on a remote system
- [X] must be "persistent" such that additional instructions/commands can be sent into the same session, bases on prior output

- have additional(?) convenience class with basic helpers to:
  - [X] write/upload,
  - [x] read/download,
  - [x] delete files,
  - [ ] create directories,
  - [ ] remove directories

__
This feature should avoid the need for ssh multiplexing (not available for windows) for any non-parallel processing.

EDIT: work is ongoing in branch https://github.com/christian-monch/datalad-next/tree/ssh-shell; tasks have been flagged as done according to the progress in that branch.

**Comment by christian-monch** [comment]
I have a question w.r.t. point 2:

> - methods to execute a command with support for iterator for stdin and reading stdout/err, and report the return code

How is the iterator for stdin supposed to be used? I am currently working on a ssh-shell command which supports the following control flow:

```python
    with ssh_connection('host.example.com') as ssh:
        # execute 'ls' on the remote host
        results = ssh.execute_command(b'ls -l /etc'):
        for line in results:
            print(line.decode())
        # check the return code of remote 'ls'-command
        if results.code == 0:
            # do something else on the remote host
            results = ssh.execute_command(b'cat /etc/fstab'):
            for line in results:
                print(line.decode())
            assert results.code == 0
```

Is that along the lines of point 2?

**Comment by mih** [comment]
Your example would be matching my "output". An example of an input iterator would be a file upload, by running `cat > somepath` on the remote end, and `cat inpath` locally via `iter_subproc` to get its "input iterator".

Does that make sense?

**Comment by christian-monch** [comment]
That makes sense.

I added the possibility to feed stdin from an iterable, e.g. an `iter_subproc`-result. This can be done after an arbitrary number of commands without stdin-redirection have been executed on the `ssh_connection`.

```python
    with \
            ssh_connection(['ssh', 'localhost']) as ssh, \
            iter_subproc(['cat', '/etc/fstab']) as fstab_cat:

        results = ssh.execute_command(b'ls -l /etc/fstab')
        for line in results:
            print('ssh:', line.decode())
        print(results.code)
        
        results = ssh.execute_command(b'cat > /tmp/test-123', stdin=fstab_cat)
        for line in results:
            print('ssh:', line.decode())
        print(results.code)
```

The only caveat is that the `ssh_connection` needs to be closed after the iterable given to `stdin=` is exhausted, so that the command executed in the subprocess (here: `cat >/tmp/test-123`) is terminated. Consequently, no more commands can be executed on `ssh` in the current `ssh_connection`-context. To execute new commands, a new `ssh_connection`-context has to be created.

**Comment by christian-monch** [comment]
> Cool. Without looking into it in depth, it feels like this requirement (only a single input generator is possible) should not be without alternative. What was the reason for your conclusion.

I might be mistaken, but I think the input-generator has to be terminated, i.e. raise `StopIteration`, if its content is redirected to `stdin` of the remotely executed command (here: `cat >/tmp/test-123`). I will try to describe the situation, it would be great if we find a different solution.

- `ssh_connect` starts an `iter_subproc`-context with a command that opens an ssh-client that connects to a host (the subprocess could also be `bash` or another interactive command, but we would usually use `ssh`, so that is what I used in the examples).
- All commands are given to `stdin` of the subprocess (the command is amended to output an "end-marker" and the exit code of the executed command, after the output of the command)
- Output of the command is received via `stdout` of the subprocess
- Individual commands are separated by newline

So, in short: `stdin` of the subprocess is used to "type in" the commands that are executed on the ssh-server, `stdout` of the subprocess is used to receive output of the command executed on the remote server plus an "end-marker" and the return code of the command.

If a remote command reads from stdin, it will only complete its processing, if its stdin-descriptor is closed. To achieve that, we have to close the stdin-descriptor of the ssh-client, i.e. the subprocess. In our case, this is done via terminating the iterator that is given to the `input=`-argument of `iter_suproc` (this is done internally by `ssh.execute_command`, if the `stdin=` parameter is provided). I don't think there is another way, and I would be happy to hear about an alternative. Once the `input`-iterator is exhausted, `iter_subproc` will not send any more data to stdin of the subprocess.

> I was thinking to let the "store command" at the remote end write out a magic marker at the end, which could be detected locally to signal the end of the remote operation.

That is done, in the example above an "end-marker" (aka "magic-marker") and the return code are written by the remote command and locally detected and processed.  The example code print the exit value of the `cat > /tmp/test-123`  command.
If the redirection is set to a non-existing directory, a return code of `1` is stored in `results.code`.

**Comment by christian-monch** [comment]
I just had the idea, why not use `dd`.  And I saw you wrote that too. Perfect. That should work.

**Comment by mih** [comment]
#596 was merged, closing. In practice there are still things to iron out, as e.g. #655 and #661 document.
